import "~/styles/globals.css";

import { GoogleAnalytics } from '@next/third-parties/google'
import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import StoreClientProvider from "./providers/store.client";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <StoreClientProvider>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </StoreClientProvider>
        <GoogleAnalytics gaId="G-JDC2LFPSEJ" />
      </body>
    </html>
  );
}
